project:
  type: website

website:
  title: "RStudio User Guide"
  favicon: images/RStudio-ball.svg
  twitter-card: true
  open-graph: true
  page-navigation: true
  site-url: https://docs.rstudio.com/ide/user/
  repo-url: https://github.com/rstudio/rstudio/tree/main/docs/user/rstudio
  repo-actions: [edit, issue]
  page-footer:
    left: |
      Copyright Â© 2022 Posit Software, PBC. All Rights Reserved.
    right:
      - icon: house-fill
        href: https://www.rstudio.com
      - icon: question-circle-fill
        href: https://support.rstudio.com/hc/en-us
      - icon: lightbulb-fill
        href: https://solutions.rstudio.com
      - icon: twitter
        href: https://twitter.com/rstudio
  navbar:
    pinned: true
    search: true
    logo: images/posit-logo-fullcolor-TM.svg
    left:
      - href: index.qmd
        text: "Overview"
      - href: ide/get-started/index.qmd
        text: "Getting Started"
      - href: ide/guide/ui/ui-panes.qmd
        text: "Guide"
      - href: ide/reference/shortcuts.qmd
        text: "Reference"
    right:
      - href: "https://posit.co"
        text: posit.co
      - href: "https://www.rstudio.com/products/rstudio/release-notes/"
        text: "Release Notes"

  sidebar:
    - id: guide
      collapse-level: 2
      contents:
      - text: "Getting Started"
        href: ide/get-started/index.qmd
      - section: "Guide"
        contents:
          - section: "Accessibility"
            contents:
              - ide/guide/accessibility/accessibility.qmd
              - ide/guide/accessibility/screen-reader.qmd
          - section: "User Interface"
            contents:
              - ide/guide/ui/ui-panes.qmd
              - ide/guide/ui/files.qmd
              - ide/guide/ui/appearance.qmd
              - ide/guide/ui/command-palette.qmd
          - section: "Code"
            contents:
              - ide/guide/code/console.qmd
              - ide/guide/code/projects.qmd
              - ide/guide/code/execution.qmd
              - ide/guide/code/diagnostics.qmd
              - ide/guide/code/debugging.qmd
              - ide/guide/code/code-sections.qmd
              - ide/guide/code/code-navigation.qmd
          - section: "Data"
            contents:
              - ide/guide/data/data-local.qmd
              - ide/guide/data/data-connections.qmd
              - ide/guide/data/connection-snippets.qmd
              - ide/guide/data/connection-contracts.qmd
          - section: "Tools"
            contents:
              - ide/guide/tools/terminal.qmd
              - ide/guide/tools/jobs.qmd
              - ide/guide/tools/jobs-in-action.qmd
              - ide/guide/tools/version-control.qmd
              # - ide/guide/integration/renv.qmd <- holding off for now
          - section: "Productivity"
            contents:
              - ide/guide/productivity/text-editor.qmd
              - ide/guide/productivity/add-ins.qmd
              - ide/guide/productivity/snippets.qmd
              - ide/guide/productivity/custom-shortcuts.qmd
              - ide/guide/productivity/project-templates.qmd
          - section: "Computational Documents"
            contents:
              - ide/guide/documents/visual-editor.qmd
              - ide/guide/documents/quarto-project.qmd
          - section: "Deploy"
            contents:
              - ide/guide/publish/connecting.qmd
              - ide/guide/publish/publishing.qmd
          - text: "Package Development"
            href: ide/guide/pkg-devel/writing-packages.qmd
          - section: "Environments"
            contents:
              - ide/guide/environments/r/managing-r.qmd
              - ide/guide/environments/r/packages.qmd
              - ide/guide/environments/py/python.qmd
      - section: "Reference"
        collapse-level: 1
        contents:
          - ide/reference/shortcuts.qmd
          


format:
  html:
    # Controls whether external links open in new windows
    link-external-newwindow: true
    # Controls whether an icon adorns external links (either true or the bootstrap icon name)
    link-external-icon: true
    number-sections: false
    theme:
      - cosmo
      - styles/styles.scss
    toc: true
    code-overflow: scroll
#  pdf:
#    toc: true
#  docx:
#    toc: true
