project:
  type: website

website:
  title: "RStudio User Guide"
  favicon: "images/favicon.svg"
  twitter-card: true
  open-graph: true
  page-navigation: true
  site-url: https://docs.posit.co/ide/user/
  repo-url: https://github.com/rstudio/rstudio/
  repo-subdir: "docs/user/rstudio/"
  repo-actions: [edit, source]
  
  navbar:
    title: "RStudio User Guide<br>{{< var buildType >}} {{< var version >}}"
    collapse: false
    pinned: true
    search: true
    logo: images/posit-icon-fullcolor.svg
    right:
      - text: Version
        menu:
          - text: 2023.06.2+561
            url: https://docs.posit.co/ide/user/2023.06.2/
          - text: 2023.06.1+524
            url: https://docs.posit.co/ide/user/2023.06.1/
          - text: 2023.03.1+446
            url: https://docs.posit.co/ide/user/2023.03.1/
          - text: Additional versions
            url: https://docs.posit.co/rsw/documentation/
      - text: "Guides"
        menu:
          - text: "Workbench Install Guide"
            url: 'https://docs.posit.co/ide/server-pro/getting_started/installation/'
          - text: "Workbench Admin Guide"
            url: 'https://docs.posit.co/ide/server-pro/'
          - text: "Posit Workbench User Guide"
            url: 'https://docs.posit.co/ide/server-pro/user/'
      - text: "Release Notes"
        url: "https://docs.posit.co/ide/news/"      
      - icon: house
        url: https://docs.posit.co/
        aria-label: Posit Documentation website
      - icon: question-circle
        url: https://support.posit.co/
        aria-label: Posit Professional Support

  sidebar:
    - id: guide
      collapse-level: 2
      contents:
      - text: "Getting Started"
        href: ide/get-started/index.qmd
      - section: "Guide"
        contents:
          - section: "Accessibility"
            contents:
              - ide/guide/accessibility/accessibility.qmd
              - ide/guide/accessibility/screen-reader.qmd
          - section: "User Interface"
            contents:
              - ide/guide/ui/ui-panes.qmd
              - ide/guide/ui/files.qmd
              - ide/guide/ui/appearance.qmd
              - ide/guide/ui/command-palette.qmd
          - section: "Code"
            contents:
              - ide/guide/code/console.qmd
              - ide/guide/code/projects.qmd
              - ide/guide/code/execution.qmd
              - ide/guide/code/diagnostics.qmd
              - ide/guide/code/debugging.qmd
              - ide/guide/code/code-sections.qmd
              - ide/guide/code/code-navigation.qmd
          - section: "Data"
            contents:
              - ide/guide/data/data-viewer.qmd
              - ide/guide/data/data-local.qmd
              - ide/guide/data/data-connections.qmd
              - ide/guide/data/connection-snippets.qmd
              - ide/guide/data/connection-contracts.qmd
          - section: "Tools"
            contents:
              - ide/guide/tools/terminal.qmd
              - ide/guide/tools/jobs.qmd
              - ide/guide/tools/jobs-in-action.qmd
              - ide/guide/tools/version-control.qmd
              - ide/guide/tools/copilot.qmd
          - section: "Productivity"
            contents:
              - ide/guide/productivity/text-editor.qmd
              - ide/guide/productivity/add-ins.qmd
              - ide/guide/productivity/snippets.qmd
              - ide/guide/productivity/custom-shortcuts.qmd
              - ide/guide/productivity/project-templates.qmd
              - ide/guide/productivity/custom-settings.qmd
          - section: "Computational Documents"
            contents:
              - ide/guide/documents/visual-editor.qmd
              - ide/guide/documents/quarto-project.qmd
          - section: "Deploy"
            contents:
              - ide/guide/publish/connecting.qmd
              - ide/guide/publish/publishing.qmd
          - text: "Package Development"
            href: ide/guide/pkg-devel/writing-packages.qmd
          - section: "Environments"
            contents:
              - ide/guide/environments/r/managing-r.qmd
              - ide/guide/environments/r/packages.qmd
              - ide/guide/environments/r/renv.qmd
              - ide/guide/environments/py/python.qmd
      - section: "Reference"
        collapse-level: 1
        contents:
          - ide/reference/shortcuts.qmd
          
          
  page-footer:
    left: |
      Copyright Â© 2022 Posit Software, PBC formerly RStudio, PBC. All Rights Reserved.
    right:
      - icon: house-fill
        href: https://www.posit.co
      - icon: question-circle-fill
        href: https://support.posit.co/hc/en-us
      - icon: lightbulb-fill
        href: https://solutions.posit.co
      - icon: twitter
        href: https://twitter.com/posit_pbc
      - text: "<img src='/images/posit-logo-black-TM.png' id='navbar-right-logo'>"
        url: "https://posit.co"


format:
  html:
    # Controls whether external links open in new windows
    link-external-newwindow: true
    # Controls whether an icon adorns external links (either true or the bootstrap icon name)
    link-external-icon: true
    number-sections: false
    fig-responsive: true
    theme:
      - cosmo
      - styles/styles.scss
    include-in-header: _ga-header-tag.html
    include-before-body: _ga-body-tag.html
    toc: true
    code-overflow: scroll

  # pdf:
  #   toc: true
  # 
  # docx:
  #   toc: true
