project:
  type: posit-docs

website:
  title: "RStudio & Posit Workbench Release Notes"
  page-navigation: true
  site-url: https://docs.posit.co/ide/news/
  search:
    copy-button: true
    show-item-context: true
  back-to-top-navigation: true
  navbar:
    pinned: true
    logo: images/posit-icon-fullcolor.svg
    title: "RStudio & Posit Workbench Release Notes"
    collapse: false
    right:
      - text: "Versions"
        url: 'https://docs.posit.co/previous-versions/rstudio/'
      - text: "Guides"
        menu:
          - text: "Posit Workbench Documentation"
            url: 'https://docs.posit.co/ide/server-pro/'
          - text: Licenses
            url: 'https://docs.posit.co/ide/server-pro/licenses/'
          - text: "RStudio Open Source User Guide"
            url: 'https://docs.posit.co/ide/user/'
      - text: "Help"
        menu:
          - text: "docs.posit.co"
            href: "https://docs.posit.co"
          - text: "Posit Support"
            href: "https://support.posit.co/hc/en-us/"

  page-footer:
    left:
      - text: <img src="/images/posit-logos-2024_horiz-full-color.svg" alt="Posit" width="65px" class="light-content posit-footer-logo"><img src="/images/posit-logo-fullcolor-TM.svg" alt="Posit" width="65px" class="dark-content posit-footer-logo">
        href: "https://posit.co"
      - Copyright Â© 2011-2025 Posit Software, PBC. All Rights Reserved.
    center: |
       RStudio & Posit Workbench Release Notes
    right:
      - text: '<a href="#" id="open_preferences_center" title="Update cookie preferences">
              <img src="/images/cookie.svg" alt="Cookie Preferences" class="light-content" style="width: 1em; height: 1em;">
              <img src="/images/cookie-copy.svg" alt="Cookie Preferences" class="dark-content" style="width: 1em; height: 1em;">
           </a>'
        aria-label: 'Cookie Prefs'
      - text: Support
        aria-label: 'Link to Posit Support'
        href: "https://support.posit.co/hc/en-us"
      - text: Posit Docs
        aria-label: 'Link to Posit Docs'
        href: "https://docs.posit.co"
        
format:
  html:
    code-overflow: scroll
    toc-expand: 1