project:
  type: posit-docs

website:
  title: "RStudio & Posit Workbench Release Notes"
  page-navigation: true
  site-url: https://docs.posit.co/ide/news/
  search:
    copy-button: true
    show-item-context: true
  back-to-top-navigation: true
  navbar:
    pinned: true
    logo: images/posit-icon-fullcolor.svg
    title: "RStudio & Posit Workbench Release Notes"
    collapse: false
    right:
      - text: "Guides"
        menu:
          - text: "Workbench Admin Guide"
            url: 'https://docs.posit.co/ide/server-pro/'
          - text: "Workbench User Guide"
            url: 'https://docs.posit.co/ide/server-pro/user/'
          - text: Workbench Licenses
            url: 'https://docs.posit.co/ide/licenses/'
          - text: "RStudio Open Source User Guide"
            url: 'https://docs.posit.co/ide/user/'
      - icon: "list"
        menu:
          - text: "docs.posit.co"
            href: "https://docs.posit.co"
          - text: "Posit Support"
            href: "https://support.posit.co/hc/en-us/"

  page-footer:
    left: |
      Copyright Â© 2011-2024 Posit Software, PBC, formerly RStudio, PBC. All Rights Reserved.
    center: |
       RStudio & Posit Workbench Release Notes
    right:
      - text: "<img src='/images/posit-guide-ltmd.svg' id='footer-right-logo'>"
        href: https://docs.posit.co
      - text: "<img src='/images/posit-logo-black-TM.svg' id='footer-right-posit-logo'>"
        href: "https://posit.co"
format:
  posit-docs-html:
    include-in-header: _ga-header-tag.html
    include-before-body: _ga-body-tag.html
    code-overflow: scroll